name: PR Build
# on:
#   pull_request:
#     branches:
#       - main
on:
  push:
    branches:
      - main
      - 'release-*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1
      - name: Try to patch if necessary
        if: ${{ contains(github.ref, 'refs/heads/release-') }}
        run: .github/scripts/patch.sh
        shell: bash
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      - name: Build with Gradle with Integration tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build integrationTests --stacktrace -PenableCoverage=true -PlocalDocker=true
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        if: ${{ matrix.os != 'ubuntu-latest' }}
        with:
          arguments: build --stacktrace -PenableCoverage=true
      - uses: codecov/codecov-action@v1
